# 2.4之前的配置
#spring:
#  profiles:
#    active: "dev"
#
#---
#spring.profiles: "dev"
#spring.profiles.include: "dev-db,dev-mq"
#
#---
#spring.profiles: "dev-db"
#
#db: dev-db.xxspace.com
#
#---
#spring.profiles: "dev-mq"
#
#mq: dev-mq.xxspace.com
#
#---

#2.4之后的配置
# 默认激活prod配置
spring:
  profiles:
    active: "test"
    group:
      "dev": "dev-db,dev-mq"
      "test": "test-db,test-mq"

---
spring:
  config:
    activate:
      on-profile: "dev-db"

db: dev-db.xxspace.com

---
spring:
  config:
    activate:
      on-profile: "dev-mq"

mq: dev-mq.xxspace.com

---
spring:
  config:
    activate:
      on-profile: "test-db"

db: test-db.xxspace.com

---
spring:
  config:
    activate:
      on-profile: "test-mq"

mq: test-mq.xxspace.com